version: '3.8'

services:
  hugo:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 1313:1313
    command:
      - sh
      - -c
      - |
        npm install
        npm run build
        hugo server --bind=0.0.0.0
